CAPTION = "THIS IS MY GAME"

#PLAYER
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 30
TANK_IMAGE = "assets/images/tank_rm.png"

SCREEN_WIDTH = 950
SCREEN_HEIGHT = 800
SCREEN_BACKGROUND_COLOR = "white"

SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
FPS = 60
